# Site
name: "University of Utah CS Women"
title: "University of Utah CS Women"
description: "Promoting the representation and interests of women in computing. "
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
mailchimp-list: 
include: ["_pages", "_officers"]
permalink: /:title/

# Authors
authors:
  cswomen:
    name: CS Women
    display_name: CSWomen
    email: uofuwomenincs@gmail.com
    avatar: '/assets/images/avatars/cswomen.png'
    twitter: 
  Anna:
    avatar: '/assets/images/avatars/xyz.png'
    display_name: Anna
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: "blog/page:num"
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  - officers
